[package]
name = "find-your-godot"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[[bin]]
name = "fyg"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
confy = "0.5"
directories = "4"
futures = "0.3"
octocrab = "0.18"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.7"
zip = { version = "0.6", default-features = false, features = ["deflate", "time"] }
