[package]
name = "too-many-godots"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
clap = { version = "4", features = ["derive"] }
confy = "0.5"
directories = "4"
futures = "0.3"
octocrab = "0.17"
reqwest = "0.11.13"
tokio = { version = "1", features = ["full"] }
zip = "0.6"
